name: Build App

on:
  push:
  pull_request:

env:
  COMPILER_VERSION: arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Toolchain
        run: wget -O /tmp/toolchain.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.3.rel1/binrel/${{ env.COMPILER_VERSION }}.tar.xz

      - name: Extract Toolchain
        run: tar -xf /tmp/toolchain.tar.xz -C /tmp

      - name: Compile App
        run: make CROSS_COMPILE=/tmp/${{ env.COMPILER_VERSION }}/bin/arm-none-linux-gnueabihf-

      - name: Upload Build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          body: "Version ${{ github.ref_name }}"
          files: |
            output/*
